# syntax=docker/dockerfile:1.20-labs

# The ARCH can be overridden by providing it a value in the command line
# with the "--build-arg=XXX" argument fed to 'docker build'.
ARG ARCH=aarch64
ARG VERSION=1.14
ARG UBUNTU_VERSION=22.04
ARG REPO=axisecp
ARG SDK=acap-native-sdk
ARG BUILD_DIR=/opt/app

FROM ${REPO}/${SDK}:${VERSION}-${ARCH}-ubuntu${UBUNTU_VERSION} AS builder

ARG BUILD_DIR
ARG ARCH

#-------------------------------------------------------------------------------
# open62541 variables
#-------------------------------------------------------------------------------
ARG OPEN62541_GIT_URL=https://github.com/open62541/open62541.git
ARG OPEN62541_VERSION=1.4.5
# open62541 sources directory name
ARG OPEN62541=open62541-${OPEN62541_VERSION}
# directory name of the build output
ARG OPEN62541_BUILD=${ARCH}-build
# full path to the git sources
ARG OPEN62541_SRC_DIR=${BUILD_DIR}/${OPEN62541}
# full path for the open62541 build output (binaries and autogenerated sources)
ARG OPEN62541_BUILD_DIR=${OPEN62541_SRC_DIR}/${OPEN62541_BUILD}

#-------------------------------------------------------------------------------
# Prepare build environment
#-------------------------------------------------------------------------------

# Install additional tools that are required but not available in the default
# docker image
RUN <<EOF
DEBIAN_FRONTEND=noninteractive
apt-get update || {
    echo "apt-get update: failed!"
    exit 1
  }
apt-get install -y --no-install-recommends \
        cmake \
        autoconf \
        libtool \
        automake || {
    echo "apt-get install: failed!"
    exit 1
  }
apt-get clean || {
    echo "apt-get clean: failed!"
    exit 1
  }
rm -rf /var/lib/apt/lists/* || {
    echo "rm -rf /var/lib/apt/lists/*: failed!"
    exit 1
  }
EOF

#-------------------------------------------------------------------------------
# Build open62541
#-------------------------------------------------------------------------------
WORKDIR ${BUILD_DIR}

# fetch the open62541 source code from the upstream Git repository and checkout
# the version pointed out by $OPEN62541_VERSION
RUN <<EOF
git clone ${OPEN62541_GIT_URL} ${OPEN62541} || {
    echo "git clone ${OPEN62541_GIT_URL}: failed!"
    exit 1
  }
cd ${OPEN62541} || {
    echo "cd ${OPEN62541}: failed!"
    exit 1
  }
git checkout v${OPEN62541_VERSION} || {
    echo "git checkout v${OPEN62541_VERSION}: failed!"
    exit 1
  }
mkdir -p ${OPEN62541_BUILD_DIR} || {
    echo "mkdir -p ${OPEN62541_BUILD_DIR}: failed!"
    exit 1
  }
EOF

WORKDIR ${OPEN62541_BUILD_DIR}
# run CMake to configure the build options for open62541
RUN <<EOF
. /opt/axis/acapsdk/environment-setup* || {
    echo "sourcing /opt/axis/acapsdk/environment-setup*: failed!"
    exit 1
  }
cmake -DCMAKE_INSTALL_PREFIX="${SDKTARGETSYSROOT}"/usr \
      -DBUILD_SHARED_LIBS=OFF \
      -DUA_LOGLEVEL=200 \
      -DUA_BUILD_EXAMPLES=OFF .. || {
    echo "cmake: failed!"
    exit 1
  }
EOF

# finally build and install open62541
RUN . /opt/axis/acapsdk/environment-setup* && make && make install

# set the working directory in the container
WORKDIR "$BUILD_DIR"

# Building the ACAP application
# copy the source code from the host filesystem into the container
COPY ./app "$BUILD_DIR"

# source the env vars required by the ACAP SDK and invoke "acap-build"
RUN . /opt/axis/acapsdk/environment-setup* && acap-build .

# copy the resulting *.eap and *LICENSE.txt files from inside the
# container to our host filesystem
FROM scratch
ARG BUILD_DIR
COPY --from=builder "$BUILD_DIR"/*eap "$BUILD_DIR"/*LICENSE.txt /
